### ISSUE TITLE
this is gross

### ISSUE THREAD

**Issue by relative** [rainyuu/startpage#1]

**Comment by radiden** [comment]
cope

**Comment by endigma** [comment]
Politics?? In my software???
Yes, politics! This is an argument made by people in all kinds of situation, and it's one that needs to die out, honestly. Here's why:

Everything is a political expression, including the lack of an opinion (which is a statement supporting the current state of affairs - something I'm sure some people making this argument are very much aware of)
Revolt is itself inherently political - it aims to be a more privacy-centric, open, transparent alternative to today's data-hoovering, closed, opaque chat apps
The Revolt team is inherently political - this is by virtue of it existing, but of course, the Code of Conduct used in official community spaces (like the Revolt server on Revolt itself) does make statements supporting the LGBT community, by taking a stance against discrimination
Taking a political stance supporting marginalized people is good, actually - especially when it's not performative
